=== fsystech/cwserver/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$comment": "This schema for app.config.json",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "Author": {
      "type": "string",
      "exclusiveMinimum": 1,
      "required": [ "Safe Online World Ltd." ],
      "const": "Safe Online World Ltd.",
      "description": "cwserver Author Name"
    },
    "appName": {
      "type": "string",
      "exclusiveMinimum": 1,
      "default": "cwserver",
      "description": "Your App name"
    },
    "version": {
      "type": "string",
      "exclusiveMinimum": 1,
      "default": "0.0.1",
      "description": "This is your app version"
    },
    "packageVersion": {
      "type": "string",
      "exclusiveMinimum": 1,
      "default": "1",
      "description": "You may use it static file version like as myfile.css?v= {= server.config.version =}"
    },
    "isDebug": {
      "type": "boolean",
      "exclusiveMinimum": 1,
      "default": true,
      "enum": [ true, false ],
      "description": "If  isDebug true then all process information will be dump in both of console and app log file "
    },
    "template": {
      "type": "object",
      "description": "Template engine",
      "exclusiveMinimum": 1,
      "default": {
        "cache": true,
        "cacheType": "FILE"
      },
      "properties": {
        "cache": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "if templateCache true, than if any template file has changed, than, it will be recompailed. Else, run from server cached file or memmory."
        },
        "cacheType": {
          "type": "string",
          "exclusiveMinimum": 1,
          "default": "FILE",
          "enum": [ "FILE", "MEM" ],
          "description": "You can set template cache mood FILE | MEM. It will be effect while template.cache is true"
        }
      }
    },
    "encryptionKey": {
      "type": "string",
      "exclusiveMinimum": 5,
      "default": "",
      "description": "This encryption key will be used _server.encryption.*.*"
    },
    "socketPath": {
      "type": "string",
      "exclusiveMinimum": 0,
      "default": "",
      "description": "While you use const {socketInitilizer} = require('cwserver');"
    },
    "staticFile": {
      "type": "object",
      "exclusiveMinimum": 1,
      "default": {
        "fileCache": true,
        "compression": true,
        "minCompressionSize": 0
      },
      "description": "Static file config",
      "properties": {
        "fileCache": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "Effected if compression is true; If fileCache true, then static file served from gzip cached file"
        },
        "compression": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "Static file compression is true then compress static file with zlib"
        },
        "minCompressionSize": {
          "type": "number",
          "exclusiveMinimum": -1,
          "default": 0,
          "description": "If minCompressionSize = 0 then all static file will be compress or compress > minCompressionSize"
        }
      }
    },
    "cacheHeader": {
      "type": "object",
      "description": "Static file browser cache header",
      "exclusiveMinimum": 1,
      "default": {
        "maxAge": "7d",
        "serverRevalidate": true
      },
      "properties": {
        "maxAge": {
          "type": "string",
          "exclusiveMinimum": 2,
          "default": "7d",
          "description": "maxAge = m = Month | d = Day | h = Hour | m = Minute."
        },
        "serverRevalidate": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "If serverRevalidate true then before served from browser cache, browser should be revalidate from server"
        }
      }
    },
    "liveStream": {
      "type": "array",
      "exclusiveMinimum": 0,
      "default": [],
      "items": {
        "type": "string"
      },
      "description": "Static file can be stream if browser support or sent range header"
    },
    "noCache": {
      "type": "array",
      "exclusiveMinimum": 0,
      "default": [],
      "items": {
        "type": "string"
      },
      "description": "Given Static file should not served from server cache"
    },
    "session": {
      "type": "object",
      "default": {
        "cookie": "_session",
        "maxAge": "1d",
        "key": "abc$#123",
        "isSecure": false
      },
      "description": "Effect on server.setSession",
      "properties": {
        "cookie": {
          "type": "string",
          "exclusiveMinimum": 1,
          "default": "_session",
          "description": "Session cookie name"
        },
        "maxAge": {
          "type": "string",
          "exclusiveMinimum": 2,
          "default": "7d",
          "description": "maxAge = m = Month | d = Day | h = Hour | m = Minute."
        },
        "key": {
          "type": "string",
          "exclusiveMinimum": 1,
          "default": "abc$#123",
          "description": "This encryption key will be use session cookie encryption"
        },
        "isSecure": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": false,
          "enum": [ true, false ],
          "description": "Session cookie send for secure connections"
        }
      }
    },
    "mimeType": {
      "type": "array",
      "exclusiveMinimum": 0,
      "default": [ "css", "js", "png", "gif", "ico", "map", "mp4", "pdf" ],
      "items": {
        "type": "string"
      },
      "description": "Define here which mim type your apps are supported"
    },
    "defaultExt": {
      "type": "string",
      "exclusiveMinimum": 0,
      "default": ".html",
      "description": "Your apps default file extension. If you set it .html or any. Suppose, your apps have /auth/login.html file extension, then this route should be /auth/login else return 404"
    },
    "bundler": {
      "type": "object",
      "description": "Static file css and js file bundler. It will use config.cacheHeader.\r\nHow to use ?\r\nIn your html or defaultExt file in script or css tag \r\nadd src/href=\"/app/api/bundle/?g={= _server.createBundle(`$root/$public/static/script/one_way_broadcast.js|__owner__`) =}&ck=index_html&ct=text/javascript&rc=Y\"",
      "default": {
        "enable": true,
        "fileCache": true,
        "route": "/app/api/bundle/",
        "compress": true
      },
      "properties": {
        "enable": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "If enable then you can use _server.createBundle"
        },
        "fileCache": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "If file chache, then served form server file cache, If any bundled file were not modified"
        },
        "route": {
          "type": "string",
          "exclusiveMinimum": 2,
          "default": "/app/api/bundle/",
          "description": "Define bundler route"
        },
        "compress": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "If bundler support compress.\r\nIf change this from previous state,\r\nplease clean $public\\web\\temp\\ folder"
        }
      }
    },
    "views": {
      "type": "array",
      "exclusiveMinimum": 0,
      "default": [],
      "items": {
        "type": "string"
      },
      "description": "All of your apps views\r\n$root = your application root __dirname\r\n$public = config.hostInfo.root"
    },
    "errorPage": {
      "type": "object",
      "description": "Application error page. If you set errorPage = {} then error page served from cwserver\r\nYou can use it from your template file or views like as ctx.next(404);\r\n$root = your application root __dirname\r\n$public = config.hostInfo.root",
      "default": {
        "404": "$root/$public/error_page/404.html",
        "401": "$root/$public/error_page/401.html",
        "500": "$root/$public/error_page/500.html"
      },
      "properties": {}
    },
    "hiddenDirectory": {
      "type": "array",
      "exclusiveMinimum": 0,
      "default": [],
      "items": {
        "type": "string"
      },
      "description": "This folder will be reserved\r\nRouter return 404 if match"
    },
    "hostInfo": {
      "type": "object",
      "description": "Application host information",
      "default": {
        "origin": [],
        "root": "www",
        "hostName": "",
        "frameAncestors": "",
        "tls": false,
        "cert": {},
        "port": 8080
      },
      "properties": {
        "origin": {
          "type": "array",
          "exclusiveMinimum": 0,
          "default": [],
          "description": "Supported origin"
        },
        "root": {
          "type": "string",
          "exclusiveMinimum": 2,
          "default": "www",
          "description": "Application public directory name"
        },
        "hostName": {
          "type": "string",
          "exclusiveMinimum": 0,
          "default": "localhost",
          "description": "Application host name"
        },
        "frameAncestors": {
          "type": "string",
          "exclusiveMinimum": 0,
          "default": "",
          "description": "content-security-policy: frame-ancestors hostInfo.frameAncestors"
        },
        "tls": {
          "type": "boolean",
          "exclusiveMinimum": 1,
          "default": true,
          "enum": [ true, false ],
          "description": "Is supported TLS (Transport Layer Security)"
        },
        "cert": {
          "type": "object",
          "exclusiveMinimum": 0,
          "default": {},
          "description": "app ssl certificate information."
        },
        "port": {
          "type": "number",
          "exclusiveMinimum": 1,
          "default": 8080,
          "description": "Which port you like to open, while not using pipe moo"
        }
      }
    },
    "database": {
      "type": "array",
      "description": "{\nmodule: string; // this is your database module name. server.db.pg.executeIo()\npath: string; // this is your database module path and it should be return ISowDatabaseType = require( database.path )\ndbConn: { database: string, password: string };\n}",
      "exclusiveMinimum": 1,
      "default": [
        {
          "module": "",
          "path": "",
          "dbConn": {
            "database": "",
            "password": ""
          }
        }
      ],
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "module": {
            "type": "string",
            "exclusiveMinimum": 1,
            "default": "",
            "description": "this is your database module name. server.db.pg.executeIo()"
          },
          "path": {
            "type": "string",
            "exclusiveMinimum": 1,
            "default": "",
            "description": "this is your database module path and it should be return ISowDatabaseType = require( database.path )"
          },
          "dbConn": {
            "type": "object",
            "exclusiveMinimum": 0,
            "default": {
              "database": "",
              "password": ""
            },
            "description": "Database connection information.",
            "properties": {
              "database": {
                "type": "string",
                "exclusiveMinimum": 1,
                "default": "",
                "description": "this connection database name"
              },
              "password": {
                "type": "string",
                "exclusiveMinimum": 1,
                "default": "",
                "description": "database password"
              }
            }
          }
        }
      }
    }
  }
}

=== fsystech/cwserver/dist/project_template/www/config/app.config.json
{
  "$schema": "../../node_modules/cwserver/schema.json",
  "Author": "Safe Online World Ltd.",
  "appName": "cwserver",
  "version": "0.0.1",
  "packageVersion": "1",
  "isDebug": true,
  "template": {
    "cache": true,
    "cacheType": "FILE"
  },
  "encryptionKey": "aaa$a",
  "socketPath": "",
  "staticFile": {
    "fileCache": true,
    "compression": true,
    "minCompressionSize": 0
  },
  "cacheHeader": {
    "maxAge": "7d",
    "serverRevalidate": true
  },
  "liveStream": [],
  "noCache": [],
  "session": {
    "cookie": "_session",
    "maxAge": "1d",
    "key": "adfasf$aa",
    "isSecure": false
  },
  "mimeType": [
    "css",
    "js",
    "png",
    "gif",
    "ico",
    "map",
    "mp4",
    "pdf"
  ],
  "defaultExt": ".html",
  "bundler": {
    "enable": true,
    "fileCache": true,
    "route": "/app/api/bundle/",
    "compress": true
  },
  "views": [ "$root/$public/lib/view/main.js" ],
  "errorPage": {
    "401": "$root/$public/error_page/401.html",
    "404": "$root/$public/error_page/404.html",
    "500": "$root/$public/error_page/500.html"
  },
  "hiddenDirectory": [],
  "hostInfo": {
    "origin": [],
    "root": "www",
    "hostName": "",
    "frameAncestors": "",
    "tls": false,
    "cert": {},
    "port": 8080
  },
  "database": []
}
